'use client'

import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { ChevronLeft, Sparkles, Lock, Gift } from 'lucide-react'
import { useReportDetail } from '@/hooks/use-reports'
import type { AdvisorReportProduct } from '@/types'
import type { ReportDetailData } from '@/hooks/use-reports'

// ── Discount prices for gift/promo reports ────────────────────────────────────

const GIFT_PROMO: Record<string, { discounted: string; original: string; tagline: string; perks: string[] }> = {
  'soulmate-sketch': {
    discounted: '$4.99',
    original: '$9.99',
    tagline: 'Your cosmic soulmate portrait — generated from your birth chart using AI',
    perks: [
      'Full visual sketch generated by AI (DALL·E)',
      'Zodiac profile: Sun, Moon & Rising of your match',
      'Karmic connection type & bond analysis',
      'Timing windows for when you\'ll meet',
      'Compatibility deep-dive across 4 life areas',
    ],
  },
  'prediction-2026-report': {
    discounted: '$7.99',
    original: '$14.99',
    tagline: 'Month-by-month cosmic forecast for love, money, and major life shifts in 2026',
    perks: [
      '12-month transit breakdown personalised to your chart',
      'Love & relationship timing windows',
      'Career & financial peak periods',
      'Health & energy cycles to plan around',
      'Retrograde impact guide for your placements',
    ],
  },
}

// ── Gift/promo unlock page ────────────────────────────────────────────────────

function GiftUnlockPage({
  product,
  detail,
  onBack,
}: {
  product: AdvisorReportProduct
  detail: ReportDetailData
  onBack: () => void
}) {
  const promo = GIFT_PROMO[product.id]
  const accent = product.accent || '#22D3EE'
  const heroImage = product.icon || '/assets/features/horoscope.png'

  return (
    <div className="flex flex-col">
      {/* Header */}
      <div
        className="sticky top-0 z-30 px-4 py-3 flex items-center gap-3"
        style={{ background: 'rgba(10,22,40,0.97)', backdropFilter: 'blur(16px)', borderBottom: '1px solid rgba(255,255,255,0.04)' }}
      >
        <button onClick={onBack} className="h-8 w-8 rounded-full flex items-center justify-center bg-white/6">
          <ChevronLeft size={16} className="text-text-secondary" />
        </button>
        <div>
          <p className="font-mystical text-[10px] text-text-muted tracking-widest">EXCLUSIVE OFFER</p>
          <h1 className="font-display text-base font-bold text-text-primary">{detail.title}</h1>
        </div>
        {/* Gift badge */}
        <div className="ml-auto flex items-center gap-1 px-2 py-0.5 rounded-full" style={{ background: 'linear-gradient(135deg, rgba(34,211,238,0.15), rgba(167,139,250,0.15))', border: '1px solid rgba(34,211,238,0.25)' }}>
          <Gift size={10} className="text-cyan-400" />
          <span className="text-[10px] font-bold text-cyan-400">Gift</span>
        </div>
      </div>

      <div className="px-4 pt-4 pb-10 space-y-4">

        {/* Hero image — blurred teaser */}
        <div className="relative rounded-3xl overflow-hidden" style={{ border: `1px solid ${accent}30` }}>
          <div className="relative h-52">
            <Image src={heroImage} alt={detail.title} fill className="object-cover" style={{ filter: 'blur(6px)', transform: 'scale(1.05)' }} unoptimized />
            <div className="absolute inset-0" style={{ background: 'linear-gradient(to bottom, rgba(10,22,40,0.4), rgba(10,22,40,0.85))' }} />
            {/* Lock overlay */}
            <div className="absolute inset-0 flex flex-col items-center justify-center gap-2">
              <div className="h-12 w-12 rounded-full flex items-center justify-center" style={{ background: `${accent}18`, border: `1px solid ${accent}40` }}>
                <Lock size={20} style={{ color: accent }} />
              </div>
              <p className="font-mystical text-base text-[#F4E2B4]">Full report locked</p>
              <p className="text-xs text-text-muted text-center px-8">Unlock your personalised AI-generated report below</p>
            </div>
          </div>
        </div>

        {/* Discount card */}
        <div
          className="rounded-3xl p-5 space-y-4"
          style={{ background: 'linear-gradient(160deg, rgba(10,22,40,0.95), rgba(15,30,53,0.98))', border: `1px solid ${accent}35` }}
        >
          {/* Price row */}
          <div className="flex items-center gap-3">
            <div>
              <p className="font-display text-2xl font-bold text-text-primary">{promo.discounted}</p>
              <p className="text-xs text-text-muted line-through">{promo.original}</p>
            </div>
            <div className="ml-auto px-2.5 py-1 rounded-full text-xs font-bold" style={{ background: 'rgba(132,204,22,0.12)', border: '1px solid rgba(132,204,22,0.3)', color: '#84CC16' }}>
              50% OFF
            </div>
          </div>

          <p className="text-xs text-text-secondary leading-relaxed">{promo.tagline}</p>

          {/* Perks */}
          <ul className="space-y-2">
            {promo.perks.map((perk) => (
              <li key={perk} className="flex items-start gap-2">
                <Sparkles size={11} className="shrink-0 mt-0.5" style={{ color: accent }} />
                <span className="text-xs text-text-secondary leading-snug">{perk}</span>
              </li>
            ))}
          </ul>

          {/* CTA */}
          <button
            className="w-full py-3.5 rounded-2xl font-display text-sm font-bold text-midnight-950"
            style={{ background: `linear-gradient(135deg, ${accent}, ${accent}bb)` }}
          >
            Unlock Full Report — {promo.discounted}
          </button>
          <p className="text-[10px] text-text-muted text-center">One-time purchase · Instant access · No subscription</p>
        </div>

        {/* Preview teaser (blurred content) */}
        <div className="space-y-2.5" style={{ filter: 'blur(4px)', pointerEvents: 'none', userSelect: 'none' }} aria-hidden>
          {detail.sections.slice(0, 2).map((section) => (
            <div key={section.title} className="rounded-2xl p-4" style={{ background: 'rgba(15,30,53,0.82)', border: `1px solid ${accent}20` }}>
              <p className="font-display text-sm font-bold mb-2" style={{ color: accent }}>{section.title}</p>
              <p className="text-sm text-text-secondary leading-relaxed">{section.body}</p>
            </div>
          ))}
        </div>

      </div>
    </div>
  )
}

// ── Main client ───────────────────────────────────────────────────────────────

interface ReportPageClientProps {
  slug: string
}

export function ReportPageClient({ slug }: ReportPageClientProps) {
  const router = useRouter()
  const { data, isLoading } = useReportDetail(slug)

  if (isLoading) {
    return (
      <div className="px-4 py-8 flex items-center justify-center">
        <span className="text-sm text-text-secondary">Loading…</span>
      </div>
    )
  }

  if (!data) {
    return (
      <div className="px-4 py-8">
        <p className="text-sm text-text-secondary">Report not found.</p>
      </div>
    )
  }

  const { product, detail: report } = data
  const heroImage = product.icon || '/features/horoscope.png'
  const accent = product.accent || '#22D3EE'

  // Gift reports → show promo unlock page instead of normal detail
  if (product.badge === 'Gift' && GIFT_PROMO[product.id]) {
    return <GiftUnlockPage product={product} detail={report} onBack={() => router.back()} />
  }

  return (
    <div className="flex flex-col">
      <div
        className="sticky top-0 z-30 px-4 py-3 flex items-center gap-3"
        style={{
          background: 'rgba(10,22,40,0.97)',
          backdropFilter: 'blur(16px)',
          borderBottom: '1px solid rgba(255,255,255,0.04)',
        }}
      >
        <button
          onClick={() => router.back()}
          className="h-8 w-8 rounded-full flex items-center justify-center bg-white/6"
        >
          <ChevronLeft size={16} className="text-text-secondary" />
        </button>
        <div>
          <p className="font-mystical text-[10px] text-text-muted tracking-widest">REPORT</p>
          <h1 className="font-display text-base font-bold text-text-primary">{report.title}</h1>
        </div>
      </div>

      <article className="px-4 pt-4 pb-8 space-y-4">
        <section
          className="rounded-3xl overflow-hidden"
          style={{
            background: 'linear-gradient(160deg, rgba(34,211,238,0.08), rgba(15,30,53,0.92))',
            border: '1px solid rgba(255,255,255,0.08)',
          }}
        >
          <div className="relative h-56">
            <Image src={heroImage} alt={report.title} fill className="object-cover" />
            <div
              className="absolute inset-0"
              style={{
                background: 'linear-gradient(to bottom, rgba(0,0,0,0.12), rgba(0,0,0,0.68))',
              }}
            />
            <div className="absolute inset-x-0 bottom-4 px-4 text-center">
              <h2 className="font-mystical text-3xl leading-tight text-[#F4E2B4]">{report.title}</h2>
              <p className="text-sm text-text-secondary">{report.subtitle}</p>
            </div>
          </div>
        </section>

        <section className="grid grid-cols-3 gap-2">
          {report.stats.map((stat) => (
            <div
              key={stat.label}
              className="rounded-2xl p-3 text-center"
              style={{
                background: 'rgba(15,30,53,0.82)',
                border: '1px solid rgba(255,255,255,0.07)',
              }}
            >
              <p className="text-[10px] uppercase tracking-wider text-text-muted">{stat.label}</p>
              <p className="font-display text-sm font-bold mt-1" style={{ color: accent }}>
                {stat.value}
              </p>
            </div>
          ))}
        </section>

        {report.sections.map((section) => (
          <section
            key={section.title}
            className="rounded-2xl p-4"
            style={{
              background: 'rgba(15,30,53,0.82)',
              border: `1px solid ${accent}35`,
            }}
          >
            <h3 className="font-display text-sm font-bold mb-2" style={{ color: accent }}>
              {section.title}
            </h3>
            <p className="text-sm text-text-secondary leading-relaxed">{section.body}</p>
            {section.bullets && section.bullets.length > 0 && (
              <ul className="mt-3 space-y-1.5">
                {section.bullets.map((bullet) => (
                  <li key={bullet} className="text-xs text-text-secondary flex items-start gap-2">
                    <span style={{ color: accent }}>•</span>
                    <span>{bullet}</span>
                  </li>
                ))}
              </ul>
            )}
          </section>
        ))}
      </article>
    </div>
  )
}
